# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-14 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersecond',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
